# Generated by Django 3.0 on 2020-08-20 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date publication')),
                ('nombrevues', models.IntegerField(null=True, verbose_name='Nombre de lecture')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['date'],
            },
        ),
    ]
